### ISSUE TITLE
Use query params when getting games from lichess

### ISSUE THREAD

**Issue by TBestLittleHelper** [Lyqst/stats-passant#1]
https://github.com/Lyqst/stats-passant/blob/421cb4724c8daa1106b18c2ed9def4ab1bd8430c/src/views/HomePage.vue#L295

Looks like you are fetching all games for a user, however you actually filtering out many games later, [like variant games.  ](https://github.com/Lyqst/stats-passant/blob/421cb4724c8daa1106b18c2ed9def4ab1bd8430c/src/views/HomePage.vue#L374)

Therefore, you could add a [perfType ](https://lichess.org/api#tag/Games/operation/apiGamesUser)query in the request, to avoid receiving games that are not used.

https://lichess.org/api/games/user/TBest?tags=true&clocks=false&evals=false&opening=false&perfType=ultraBullet%2Cbullet%2Cblitz%2Crapid%2Cclassical%2Ccorrespondence%2Ccrazyhouse%2Cchess960

For example [Pawn_Street_Blues ](https://lichess.org/@/Pawn_Street_Blues)has 200 000+ variant games that you don't need to request :)  (unless you also want to incude KotH)
Might also be nice to offer a date option (1 day/week/month/forever) , like Rosen Score recently added. So that players with tons of games, can look at a smaller sample. 

En passant, what a great site you have made!

**Comment by Lyqst** [comment]
Hey, good catch! Will certainly implement this.

I am planning to add more filters (similar to what OpeningTree does) soon.
